[features]
seeds = false
skip-lint = false
[programs.devnet]
bus_trip_ticket = "Cmyo3foHLuN7X48qiUBXdXzwz6hMjMebcQ2v3YzUKVp8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
register = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Bus/RegisterBus.ts"
