[features]
seeds = false
skip-lint = false
[programs.devnet]
bus_trip_ticket = "2M8bks58FxtThuuFuazvsA2skRJi3M4Pk6qxEsQiz7g5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
register = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Bus/RegisterBus.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/User/CheckIt.ts"
trip = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/User/TakeATrip.ts"
change_prices = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Bus/ChangePrices.ts"
lines = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/User/BusesLines.ts"
enable = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/User/EnableCard.ts"
balance = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/User/ChargeBalance.ts"
st = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/User/UserStatistics.ts"